%% Raul Zayas 10/6/20 Water Wheel Optimization %%
%% 
clc, clear
%% Variables (US customary)
g = 32.2; % gravity 
oD = (6); % Outer Diameter wheel
r = oD/2; % Outer Radius wheel
fd = (3); % Height of water falling 
Cf = (0.8); % Coefficient of Friction (concrete on concrete)
sD = 0.09935005; % Sorel Cement density
mr = 5; % Millstone radius
mh = 2; % Millstone thickness
mR = 60; % Millstone RPM
theta = pi/2;
C = 2*pi*r; % Circumference of wheel 
WD = oD + fd'; % Working Diameter
E = 0.7; % Efficiency of wheel
%% Formulas
Vol = pi*mr.^2*mh; % Volume
M = sD*Vol; % Mass 
F = M; % Normal Force
fF = F*Cf;% Friction Force 
T = (mr./12)*fF*sin(theta) % Torque Required (lb-ft)
HP = (T*mR)./5252
v = sqrt(2*g*fd); % velocity of the water due to fall (ft/s)
EWS = .93*v*60; % wheel speed at 93% efficieny (ft/m)
RPM = EWS./C' % Wheel rpm (Diameter descending rows, Increasing water velocity in the columns)
Q = 0.148; % Quantity of Water at a Given diameter ft^3/s 
Qg = Q*448.8  % Gallons per min
PW = ((Q.*WD)/11.8) % Power Generated in KWs
HPW = PW./(.746) % HP generated by Water Wheel

